### ISSUE TITLE
Dataset Info Sidebar doesn't resize properly

### ISSUE THREAD

**Issue by pdeperio** [coderdj/emo#10]
In the attached image, both the main browser and dataset sidebar are scrolled all the way down, however, we still can't see all the dataset locations.

<img width="1345" alt="screen shot 2016-12-02 at 3 09 33 pm" src="https://cloud.githubusercontent.com/assets/8642192/20850574/77ace676-b8a1-11e6-9645-08e3d3e9825c.png">

**Comment by l-althueser** [comment]
Workaround for this: You can zoom out the page to see everything ...

**Comment by coderdj** [comment]
Fixed in 75b7425bba6c0b8765efc4c568508b848d9767b3. Reopen if not. Or reduce data sites. ;-)
