### ISSUE TITLE
Run mode inheritance

### ISSUE THREAD

**Issue by JelleAalbers** [coderdj/emo#15]
Many settings are common to several runmodes yet must occasionally be changed. To prevent mistakes like we discovered today where the self-trigger thresholds for calibration runmodes are different than for background runmodes, it would be useful to have an inheritance system. For example, rn220_stable inherits all settings from background_stable and just updates the source name. I'm not sure how difficult this is to do, but I don't think we need fancy stuff like multiple inheritance or several levels.

**Comment by coderdj** [comment]
Closed in 6d261a258e39c44e06fdf05869458914b9fc51fe.

Just have to test a few things then I'll migrate all TPC run modes to 'inherited' versions.
