### ISSUE TITLE
 The main rate history graph does not show the time

### ISSUE THREAD

**Issue by ghost** [coderdj/emo#17]
Hello (Dan)

On the shifter2 tablet daq control screen, the main rate history graph does not show the time,
as indicated at the attached image.
Restarting the tablet did not fix this issue.
(On my computer, and on the other shifter's table, the page shows well).

Thanks
  David Front (dfrontdfront, dfront@gmail.com, dfront@skype)

![daqscreen](https://cloud.githubusercontent.com/assets/24654713/21428158/4d7144a4-c861-11e6-8f89-a33ec1ad6cae.jpg)

**Comment by l-althueser** [comment]
Did you have reloaded the page after changing to landscape view? If you not reload the page the internal zoom of the app can cause this (I saw the same on shifter1 tablet ;) )

**Comment by ghost** [comment]
Hello

Indeed, reloading by itself did not help,
but changing orientation and then reloading dies 'fix' the issue, the time
shows.

Thanks for this 'work around'!
  Marry Christmas
   David

**Comment by coderdj** [comment]
Looks fine on smartphone after a8a8227feccbf7c767ae0b84d1be3e8b9d81da16
