### ISSUE TITLE
I suggest that time at the time at trigger status window will be bigger and bold

### ISSUE THREAD

**Issue by ghost** [coderdj/emo#18]
Hello Dan

I suggest that time at the time at trigger status window will be bigger and bold,
because it is supposed to help the user be aware if the screen is uptodate or not.

Thanks
  David

**Comment by coderdj** [comment]
Commit 0f54556f66e0b1e175be4c757504d9fc0b7adf80 adds a red indicator any time this value is more than a minute old warning the user that the trigger is behind for some reason (note that this is normal in case the DAQ is stopped or the trigger is not running).
