### ISSUE TITLE
Add a runMode column to the runs screen

### ISSUE THREAD

**Issue by ghost** [coderdj/emo#19]
Hello Dan

I suggest to add a runMode column to the runs screen.
Currently, this information is 'hidden' within the jason,
and we, as shifters, (usually) add the run mode as part of the comment.
When the comment is not edited to have the runMode, 
it is not easy to see from the runs screen what was the runMode,
and I suggest that comment should be for (other) things that unique to the run.

Thanks
  David Front

**Comment by coderdj** [comment]
Closed in a128d65f08ec1667065612160163e11eabbf5ff5

**Comment by ghost** [comment]
Thanks!
