### ISSUE TITLE
confused presentation of runs

### ISSUE THREAD

**Issue by ghost** [coderdj/emo#23]
When selecting to see muonveto runs,
sometimes tpc runs show instead,
as appears in the example image:

![screenhunter_2862 dec 29 18 59](https://cloud.githubusercontent.com/assets/24654713/21549227/7539dc74-cdf9-11e6-8a5c-eec7563cd636.jpg)

**Comment by coderdj** [comment]
Closed in a9978f0bbb58209e34d5332b6c681a4eeedbfe2c
