### ISSUE TITLE
Expand shift calendar functionality

### ISSUE THREAD

**Issue by coderdj** [coderdj/emo#24]
Or just remove it from the webpage. This sounds like the most reasonable option.

However if we're going to use this the following features are needed:
- Generate shift rules for a year without nuking current shifts
- Allow rollover from previous year
- Allow removing users from collaboration list (not really remove but set departure date)
- Allow adding or renaming an institute via form. 

Suggestion:
1. One function to add 'empty' shifts to a date range with certain properties (length of shift, day they start). This is already there, just have to gimp it a bit to prohibit overriding of already signed up shifts.
2. One function to generate a rule doc valid for a particular date range (note: can't allow overlap with other ranges, have to have option to roll over from previous, etc). 
3. One additional field for users called 'departure date'. This is None for anyone still in XENON and a datetime for people that left. Needs to be added to update form (and allowed to be empty) and to responsibility calculation logic.
4. "Adding removing institute via form" is for a student who wants to learn javascript. I'll just hardcode the changes in this time.

**Comment by tunnell** [comment]
I didn't think Marcello wanted rollover?
