### ISSUE TITLE
Trigger monitor page bug

### ISSUE THREAD

**Issue by pizzella** [coderdj/emo#25]
In the trigger monitor page the last channel of each interval selectable from the dropdown menu is not visible in the legend at the side of the pulses graphs. For example, if the channels 0-11 are selected, only the channels up to 10 are visible at the side. Consequently, it is not possible to hide the last channel of each interval.

I didn't manage to upload a picture, sorry!

**Comment by coderdj** [comment]
Easiest would be to just make the page bigger.

**Comment by pizzella** [comment]
I'm not sure this is the problem. I tried both on the shifter's tablet and with my laptop and it doesn't change the format. I always see the last channel missing

**Comment by coderdj** [comment]
I can confirm it looks fine on both chrome and edge on a PC.

**Comment by ariannarocchetti** [comment]
I have the same issue on my laptop. I confirm that in a bigger screen everything works fine, but on my laptop (the same in Dominick's) we can`t see the last two channels. I would say it depends on the dimensions of the screen.

**Comment by coderdj** [comment]
See 48bbae3214dcb53f9e1f86c740a58ccf0504cc39
