### ISSUE TITLE
Unable to write tags

### ISSUE THREAD

**Issue by ErikHogenbirk** [coderdj/emo#29]
Since yesterday I'm not able to write tags in the runs database any more, but only on PC. I tried both Firefox and Chrome. When I click 'add tag', a popup appears that says 'are you sure you want to add this tag?', but it disappears very quickly so that I cannot press yes. Adding tags works fine on a tablet.

**Comment by coderdj** [comment]
Can't reproduce on either chrome or firefox. Works fine. Try clearing your cache?

**Comment by ErikHogenbirk** [comment]
Did not fix the issue. Junji has the same problem, so does the Slow Control PC in lab 2...

**Comment by l-althueser** [comment]
The "new Tag" button in the runs database works fine for me (but there is no confirmation popup). I can add and delete tags on recent Firefox and Edge versions.

**Comment by ErikHogenbirk** [comment]
Chrome version 57.0.2987.133. Just updated to version 58.0.3029.81 and issue persists. Firefox version 53.0 (64-bits). Edge version 38.14393.1066.0 . All the same issue. I include a screenshot of the popup.

![image](https://cloud.githubusercontent.com/assets/9975649/25580837/36c96720-2e84-11e7-8922-07db1db9049e.png)

**Comment by l-althueser** [comment]
It was again possible for me to add a "blinded" tag to run 9189, as you can see in the db. No popup for me!

**Comment by ErikHogenbirk** [comment]
Browser version number?

**Comment by l-althueser** [comment]
I removed the tag. Here is a screenshot:
![screenshot 7](https://cloud.githubusercontent.com/assets/13698969/25581148/4533b3c2-2e86-11e7-91b3-955b59a78966.png)
Edge 40.15063

**Comment by l-althueser** [comment]
My "old" Firefox 52.0.2 (32-Bit) has the issue with the very short popup (and a direct page reload)! So there is some kind of bug somewhere ..

**Comment by ErikHogenbirk** [comment]
Fixed, thank you!
