### ISSUE TITLE
showing queue's end on DAQ Control Panel page

### ISSUE THREAD

**Issue by NataschaRupp** [coderdj/emo#6]
It would be good to have a field on the DAQ Control Panel page where we could see how many runs are in the queue or/and when the last run in the queue will be finished.

**Comment by coderdj** [comment]
Thanks for the feedback. I'm implementing an update to the playlist functionality in the coming week or so and will include this suggestion in the new frontend. If you have further suggestions please let me know.

**Comment by coderdj** [comment]
I think the recent update addresses this. If not reopen.
